"""removed admin_questions table

Revision ID: 0dcef0d1dd67
Revises: be1e660b6b77
Create Date: 2025-02-21 00:47:59.195587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dcef0d1dd67'
down_revision: Union[str, None] = 'be1e660b6b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_questions_id', table_name='admin_questions')
    op.drop_table('admin_questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('option_a', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('option_b', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('option_c', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('option_d', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('correct_option', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admin_questions_pkey')
    )
    op.create_index('ix_admin_questions_id', 'admin_questions', ['id'], unique=False)
    # ### end Alembic commands ###
