"""Updated questions table

Revision ID: 5d914bc29de9
Revises: ed34ada8e506
Create Date: 2025-02-17 15:04:32.330542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d914bc29de9'
down_revision: Union[str, None] = 'ed34ada8e506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('category', sa.String(), nullable=False))
    op.add_column('questions', sa.Column('difficulty', sa.String(), nullable=False))
    op.alter_column('questions', 'question_text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('questions', 'difficulty')
    op.drop_column('questions', 'category')
    # ### end Alembic commands ###
