"""Added level column into questions table

Revision ID: 658c0d67a5ca
Revises: a4f0e1d53a98
Create Date: 2025-02-18 17:00:27.687536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658c0d67a5ca'
down_revision: Union[str, None] = 'a4f0e1d53a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('level', sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'level')
    # ### end Alembic commands ###
