"""added admincreated column in questions table

Revision ID: 6af3b58238cf
Revises: 0dcef0d1dd67
Create Date: 2025-02-21 00:56:14.272206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af3b58238cf'
down_revision: Union[str, None] = '0dcef0d1dd67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('admincreated', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    # If needed, remove the default constraint after migration
    op.alter_column('questions', 'admincreated', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'admincreated')
    # ### end Alembic commands ###
