"""Add show_answer column

Revision ID: 8fb640ae4fc1
Revises: 0d48742c743c
Create Date: 2025-02-19 22:27:54.439441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb640ae4fc1'
down_revision: Union[str, None] = '0d48742c743c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('show_answer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'show_answer')
    # ### end Alembic commands ###
