"""remove show_answer column

Revision ID: 928250168724
Revises: 8fb640ae4fc1
Create Date: 2025-02-19 22:37:14.114587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928250168724'
down_revision: Union[str, None] = '8fb640ae4fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'show_answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('show_answer', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
