"""Added session id column to the QuizAttempt table

Revision ID: a4f0e1d53a98
Revises: b37b44504486
Create Date: 2025-02-18 14:20:46.263498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f0e1d53a98'
down_revision: Union[str, None] = 'b37b44504486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add session_id with a NULLABLE constraint temporarily
    op.add_column('quiz_attempts', sa.Column('session_id', sa.Integer(), nullable=True))

    # Backfill old records with a default session_id
    op.execute("UPDATE quiz_attempts SET session_id = id")  # Assigns each row a unique session ID

    # Set session_id as NOT NULL
    op.alter_column('quiz_attempts', 'session_id', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_attempts', 'session_id')
    # ### end Alembic commands ###
