"""Add back level column

Revision ID: dd86a7c6fbe2
Revises: 8acd27951ad2
Create Date: 2025-02-18 18:02:44.894802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd86a7c6fbe2'
down_revision: Union[str, None] = '8acd27951ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'level')
    # ### end Alembic commands ###
