"""update column in admins table

Revision ID: feb470a0c72f
Revises: 1cf3971178c6
Create Date: 2025-02-20 00:21:44.967699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb470a0c72f'
down_revision: Union[str, None] = '1cf3971178c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('admins', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('admins', 'hashed_password')
    # ### end Alembic commands ###
